#!/usr/bin/env node

'use strict';

const _ = require('lodash');
const fs = require('fs');
const c = require('colors');

const out = `${__dirname}/data/athletes-top.json`;

function combine() {
  const clubActivities = {};
  const athletes = {};
  let dataFiles = 0;

  // collect club activities from all data files
  for (const f of fs.readdirSync(__dirname + '/data/dumps').sort()) {
    dataFiles++;

    try {
      const activities = require(`${__dirname}/data/dumps/${f}`);
      for (const activity of activities) {
        clubActivities[activity.id] = activity;
      }
    } catch (e) {
      console.error(`Unable to read data file "${f}"`);
    }

  }

  // [info]
  console.log(c.cyan('Data files:\t\t') + dataFiles);
  console.log(c.cyan('Activities:\t\t') + _.values(clubActivities).length);

  // group activities by athlete

  let m = 0;

  for (const a of _.values(clubActivities)) {
    if (!athletes[a.athlete.id]) athletes[a.athlete.id] = [];
    athletes[a.athlete.id].push(a);
  }

  // create by-athlete summary

  const athletesTop = [];

  for (const activities of _.values(athletes)) {
    const athlete = activities[0].athlete;

    athletesTop.push({
      athleteName: athlete.firstname + ' ' + athlete.lastname,
      distance: activities.map(e => e.distance).reduce((a, b) => a + b) / 1609.34 /* meters/mile */,
      movingTime: activities.map(e => e.moving_time).reduce((a, b) => a + b)
    });
  }

  athletesTop.sort((a, b) => b.distance - a.distance);

  // [info]
  console.log(c.cyan('Athletes:\t\t') + _.values(athletes).length);

  // save to file
  fs.writeFileSync(out, JSON.stringify(athletesTop));
  console.log(c.cyan('File created:\t\t') + out);
}

combine();