#!/usr/bin/env node

'use strict';

const fs = require('fs');
const c = require('colors');
const _ = require('lodash');
const config = require('./config');
const common = require('./common');
const promiseWhile = require('./lib/promise-while');

const out = `${__dirname}/data/club-athletes-stats.json`;

function main() {

  const athletesData = {};

  common.getAthletes(config.club_id, config.access_token)
    .then(clubAthletes => {
      console.log(c.magenta('Got ') + clubAthletes.length + c.magenta(' athletes'));
      return promiseWhile(
        () => clubAthletes.length > 0,
        () => {
          return common
            .getAthleteStats(clubAthletes.shift().id, config.access_token)
            .then(athlete => {
              console.log(athlete);
              console.log(c.cyan('Fethced ') + athlete.firstname + ' ' + athlete.lastname);
              athletesData[athlete.id] = athlete;
            });
        }
      )
    })
    .then(() => {
      // save to file
      fs.writeFileSync(out, JSON.stringify(athletesData));
      console.log(c.yellow('File created:\t\t') + out);
    })
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
}

main();